
export const LIST_GAME_MODES_REQUESTED = 'LIST_GAME_MODES_REQUESTED';
export const LIST_GAME_MODES_SUCCESS = 'LIST_GAME_MODES_SUCCESS';
export const LIST_GAME_MODES_FAILURE = 'LIST_GAME_MODES_FAILURE';

export const listGameModes = () => ({ type: LIST_GAME_MODES_REQUESTED });
