language: node_js

node_js:
- 12.13.0

env:
  global:
  - KUBECONFIG="/etc/deploy/config"
  - CONTAINER_NAME="strooped/strooped-master:${TRAVIS_COMMIT}"
jobs:
  include:
  - stage: Quality
    name: ESLint
    script: npm run lint:js
  - script: npm run lint:styles
  - stage: Test
    name: Unit-test
    script: npm run test:coverage
  - stage: Dependency Audit
    script: npm audit || true
    # Our cluster runs on raspberry PIs
  - stage: build docker image
    language: bash
    os: linux
    arch: arm64
    script:
      - echo "$DOCKER_SECRET" | docker login -u "$DOCKER_USER" --password-stdin
      - docker build -t $CONTAINER_NAME .
      - docker images
      - docker push $CONTAINER_NAME

# before_install...gs
# openssl aes-256-cbc -K $encrypted_b2c29de587db_key -iv $encrypted_b2c29de587db_iv -in deploy_key.enc -out deploy_key -d
