apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ CI_PROJECT_NAME }}
  namespace: {{ KUBE_NAMESPACE }}
spec:
  selector:
    matchLabels:
      app: {{ CI_PROJECT_NAME }}
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 10%
  template:
    metadata:
      labels:
        app: {{ CI_PROJECT_NAME }}
    spec:
      containers:
        - image: strooped/{{ CI_PROJECT_NAME }}:{{ CI_COMMIT_SHORT_SHA }}
          name: app
          ports:
            - containerPort: 3000
              name: app
          env:
            - name: NODE_ENV
              value: "production"
          # Tells kubernetes whether or not the pod is ready to receive requests
          readinessProbe:
            httpGet:
              path: /favicon.ico
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 5
          # Tells it whether or not the application should be restarted or not. ex. from deadlock
          livenessProbe:
            httpGet:
              path: /favicon.ico
              port: 3000
            initialDelaySeconds: 60
            timeoutSeconds: 10
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: {{ CI_PROJECT_NAME }}
  namespace: {{ KUBE_NAMESPACE }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: {{ CI_PROJECT_NAME }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ CI_PROJECT_NAME }}-ingress
  namespace: {{ KUBE_NAMESPACE }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - strooped.lokalvert.tech
      secretName: tls-secret
  rules:
    - host: strooped.lokalvert.tech
      http:
        paths:
            - path: /
              backend:
                serviceName: {{ CI_PROJECT_NAME }}
                servicePort: 3000
